package com.revesoft.itelmobiledialer.util;


public interface Constants {
	public static final String tag = "VideoDialer",
			USERNAME = "username",
			USERNAME_DEF = "",
			PASSWORD = "password",
			PASSWORD_DEF = "",
			PIN = "PIN",
			PHONE = "phone",
			PHONE_DEF = "",
			AUTOSTART = "autostart",
			OP_CODE = "op_code",
			OP_CODE_DEF = "",
			NUMBER = "number",
			ID = "id",
			TYPE = "type",
			TIME = "time",
			DURATION = "duration",
			to1 = "to1",
			to2 = "to2",
			to3 = "to3",
			compose = "compose",
			TOPUP_PORT = "topupPort",
			TOPUP_IP = "topupIP",
			COUNTRY = "country",
			COUNTRY_DEF = "",
			OPERATOR = "operator",
			OPERATOR_DEF = "",
			TOPUP_TYPE = "topup_type", 
			TOPUP_TYPE_DEF = "",
			DIALER_INTENT_FILTER = "com.revesoft.itelmobiledialer.dialerguiintent",
			SIGNUP_INTENT_FILTER = "com.revesoft.itelmobiledialer.signupintent",
			PRESENCE_INTENT_FILTER = "com.revesoft.itelmobiledialer.messageintent",
			MESSAGE_INTENT_FILTER = "com.revesoft.itelmobiledialer.messageintent",
			SWITCH_IP = "switch_ip", SWITCH_PORT = "switch_port",
			SWITCH_IP_DEF = "0.0.0.0", SWITCH_PORT_DEF = "0", IVR = "ivr",
			IVR_DEF = "";
	public static final boolean AUTOSTART_DEF = false;
	public static final int PROXIMITY_SCREEN_OFF_WAKE_LOCK = 32,
			SIGNUP_REQUEST = 100, REGISTRATION_VERIFICATION_REQUEST = 101,
			VOICE_CALL_REQUEST = 102;

	public static final String TYPE_INCOMING = "incoming",
			TYPE_INCOMING_DEF = "", TYPE_OUTGOING = "outgoing",
			TYPE_OUTGOING_DEF = "",
			BROADCAST_MESSAGE_FROM_DIALER = "from_dialer",
			BROADCAST_MESSAGE_FROM_CALL = "from_call",
			BROADCAST_MESSAGE_NUMBER = "number",
			BROADCAST_MESSAGE_NUMBER_DEF = "",
			INTENT_FROM_INCALL = "com.revesoft.dialer.broadcastfromcall",
			INTENT_FROM_DIALER = "com.revesoft.dialer.broadcastfromdialer",
			BROADCAST_MESSAGE_DISPLAY_STATUS = "display_status",
			BROADCAST_MESSAGE_SEND_DTMF = "send_dtmf",
			BROADCAST_MESSAGE_FINISH = "display_status",
			BROADCAST_MESSAGE_DISPLAY_DURATION = "display_duration",
			BROADCAST_MESSAGE_START_VIDEO_RECEIVING = "start_video_receiving",
			BROADCAST_MESSAGE_ACCEPT = "accept",
			BROADCAST_MESSAGE_REJECT = "reject", HOME_KEY_EXIT = "homekeyexit",
			BROADCAST_MESSAGE_START_SPEAKER = "start_speaker",
			BROADCAST_MESSAGE_STOP_SPEAKER = "stop_speaker",
			BROADCAST_MESSAGE_START_SOUND = "start_sound",
			BROADCAST_MESSAGE_STOP_SOUND = "stop_sound",
			BROADCAST_MESSAGE_START_BLUETOOTH = "start_bluetooth",
			BROADCAST_MESSAGE_STOP_BLUETOOTH = "stop_bluetooth",
			BROADCAST_MESSAGE_START_MUTE = "start_mute",
			BROADCAST_MESSAGE_STOP_MUTE = "stop_mute";
}
